# fly.toml app configuration file generated for funprojects-silent-wildflower-5853 on 2025-10-03T18:35:20+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'funprojects-silent-wildflower-5853'
primary_region = 'otp'

[http_service]
  internal_port = 80
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
